import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Cinzel } from "next/font/google";

const cinzelDecorative = Cinzel({
  subsets: ["latin"],
  weight: ["400"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Song of Ice and Fire",
  description: "Generated by next and tailwind",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🐲</text></svg>"></link>
      <body className={`${cinzelDecorative.className} bg-slate-500`}>{children}</body>
    </html>
  );
}
